export const amiLabels = {
  pageTag: '2.3 即時AMI電量監控',
  pageTitle: 'AMI 發用電量與入系統狀態',
  pageDescBefore: '進入畫面預設顯示',
  pageDescToday: '今日',
  pageDescAfter: '各表最新入系統電量；可選擇其他日期查詢歷史 AMI 授權資料。AMI 入系統約落後配電即時',
  pageDescHours: '小時',
  selectAgent: '選擇代理人',
  allAgents: '全部代理人',
  allAgentsGenSubtitle: '所有代理人 · 發電 AMI 表號',
  allAgentsLoadSubtitle: '所有代理人 · 用電 AMI 表號',
  queryDate: '查詢日期',
  backToday: '回到今日',
  refresh: '立即更新',
  liveMode: '即時模式 · 上次更新',
  historyMode: '歷史模式 ·',
  genMeterCount: '發電端 AMI 表數',
  loadMeterCount: '用電端 AMI 表數',
  latestSum: '最新入系統合計',
  lagTitle: '最新入系統落差',
  lagHistory: '歷史日期不計落差',
  systemLatest: '系統最新',
  ingestTitle: '資料進系統狀態',
  ingestNormal: '正常收檔',
  ingestDelayed: '延遲收檔',
  ingestHistory: '歷史完整',
  ingestDetail: '發電已入系統',
  ingestLoadDetail: '用電已入系統',
  apiTitle: 'API 介接與歷史下載',
  apiRealtime: '即時量測 API：',
  apiHistory: '歷史授權 API：',
  dlGen: '下載',
  dlGenSuffix: '發電歷史 CSV',
  dlLoadSuffix: '用電歷史 CSV',
  searchPh: '搜尋 AMI 表號 / 案場 / 電號 / 代理人',
  trendToday: '趨勢圖各整點為各表該時刻 15 分鐘區間電量加總（與 CSV 整點列、系統明細同一公式）；參考線為資產堆疊之',
  trendHoliday: '假日',
  trendWeekday: '平日',
  trendShape: '形態',
  trendHistory: '趨勢圖顯示',
  trendHistorySuffix: '全日已入系統電量',
  genLatestTitle: '發電端最新入系統明細',
  genHistoryTitle: '發電端歷史入系統明細',
  genSubtitle: '聚合發電 AMI 表號',
  loadLatestTitle: '用電端最新入系統明細',
  loadHistoryTitle: '用電端歷史入系統明細',
  loadSubtitle: '聚合用電 AMI 表號',
  chartLive: '實線=已入系統｜虛線=',
  chartRef: '參考預測',
  chartHistoryNote: '（歷史日完整顯示）',
  gen: '發電',
  load: '用電',
  noAgent: '尚無代理人資料',
  meterCountPrefix: '共',
  meterCountSuffix: '個 AMI 表號',
  genSide: '發電端',
  loadSide: '用電端',
  colMeter: 'AMI 表號 / 案場',
  colKwh: '最新入系統電量',
  colInterval: '時間',
  colIngest: '入系統時間',
  colLag: '與當下落差',
  colAgent: '代理人',
  lagAbout: '約',
  lagUnit: '小時',
  historyRow: '歷史資料',
  noMeter: '此代理人尚無',
  noMeterSuffix: '端表號',
  total: '合計',
  footToday: '各表最新一筆入系統區間電量加總',
  footHistory: '',
  chartNotIn: '（尚無表號入系統）',
  chartPartial: '已入系統表號',
  chartInSystem: '已入系統電量',
  chartHoliday: '假日參考形態',
  chartWeekday: '平日參考形態',
  chartGen: '發電端',
  chartLoad: '用電端',
  chartTrend: '電量趨勢',
  csvGen: '發電',
  csvLoad: '用電',
  csvAuth: '已授權',
  csvPending: '待入系統',
  csvHeaders: ['代理人', 'AMI表號', '案場名稱', '區間時間', '區間電量kWh', '授權狀態'],
  csvIntervalNote: '歷史 CSV 為每 15 分鐘一筆（96 列／表／日）',
} as const;
