import type { StorageFormField } from '@/types';

export const STORAGE_FORM_FIELDS: StorageFormField[] = [
  { id: 'elecNo', label: '電號 (必填)*', type: 'number' },
  { id: 'meterNo', label: '表號', type: 'number' },
  { id: 'power', label: '裝置功率 (kW)', type: 'number' },
  { id: 'capacity', label: '裝置電量 (kWh)', type: 'number' },
  { id: 'chargeEff', label: '儲能充電效率 (%)', type: 'number' },
  { id: 'dischargeEff', label: '儲能放電效率 (%)', type: 'number' },
  { id: 'taxId', label: '公司統編 (電廠ID)', type: 'number' },
  { id: 'genId', label: '發電機組ID', type: 'number' },
  { id: 'resCode', label: '資源代碼 (UNIT_RES表)', type: 'number' },
  { id: 'accountName', label: '戶名', type: 'text' },
  { id: 'resAddress', label: '資源所在地址', type: 'text' },
  { id: 'resZip', label: '資源所在郵遞區號', type: 'number' },
  { id: 'maxNetOutput', label: '最大淨出力 [MW]', type: 'number' },
  { id: 'minNetOutput', label: '最小淨出力 [MW]', type: 'number' },
  { id: 'approvedCapacity', label: '核定參與容量', type: 'number' },
  { id: 'elecNo2', label: '電號 (輔助)', type: 'number' },
  { id: 'ami1', label: 'AMI表號1', type: 'number' },
  { id: 'ami2', label: 'AMI表號2', type: 'number' },
  { id: 'ami3', label: 'AMI表號3', type: 'number' },
  { id: 'ami4', label: 'AMI表號4', type: 'number' },
  { id: 'gridVoltage', label: '併網電壓', type: 'number' },
  { id: 'regStatus', label: '註冊狀態(2、4)', type: 'number' },
  { id: 'opDate', label: '正式營運日期', type: 'date' },
  { id: 'lastUpdateTime', label: '最後更新時間', type: 'datetime-local' },
  { id: 'lastUpdateUser', label: '最後更新人員編號', type: 'number' },
  { id: 'resTypeCode', label: '資源類別代碼', type: 'number' },
  { id: 'marginStatus', label: '保證金狀態', type: 'number' },
  { id: 'accountName2', label: '戶名 (輔助)', type: 'text' },
  { id: 'lineLossFactor', label: '併網儲能線路損失調整因子', type: 'number' },
  { id: 'capacityMw', label: '裝置容量 MW', type: 'number' },
  { id: 'maxRampUp', label: '最大升載率 MWMin', type: 'number' },
  { id: 'maxRampDown', label: '最大降載率 MWMin', type: 'number' },
  { id: 'minUptime', label: '最小運轉時間 h', type: 'number' },
  { id: 'minDowntime', label: '最小停機時間 h', type: 'number' },
  { id: 'peakGuaranteedCap', label: '尖峰時段保證容量 kW', type: 'number' },
  { id: 'maxStorageCap', label: '儲能最大容量 MWh', type: 'number' },
  { id: 'maxStorageOutput', label: '儲能最大輸出功率 MW', type: 'number' },
  { id: 'drContractCap', label: '需量反應經常契約容量 MW', type: 'number' },
  { id: 'resOwnership', label: '資源歸屬', type: 'number' },
  { id: 'agentName', label: '代理資源公司名稱', type: 'text' },
  { id: 'agentAddress', label: '代理資源登記地址', type: 'text' },
  { id: 'agentZip', label: '代理資源郵遞區號', type: 'number' },
  { id: 'agentContact', label: '代理資源聯絡人', type: 'text' },
  { id: 'agentTitle', label: '聯絡人職稱', type: 'text' },
  { id: 'agentPhone', label: '聯絡人電話', type: 'number' },
  { id: 'agentMobile', label: '聯絡人手機', type: 'number' },
  { id: 'agentEmail', label: '聯絡人電子郵件', type: 'text' },
  { id: 'transferCap', label: '移轉容量', type: 'number' },
  { id: 'ptRatio', label: '變比器的倍數', type: 'number' },
  { id: 'ptAccuracy', label: '比壓器PT精確度', type: 'number' },
  { id: 'ctAccuracy', label: '比流器CT精確度', type: 'number' },
  { id: 'meterAccuracy', label: '交易表計精確度', type: 'number' },
  { id: 'gridVoltageLevel', label: '併網電壓等級kV', type: 'number' },
  { id: 'isAggregated', label: '低於100kW之聚合資源(0否1是)', type: 'number' },
  { id: 'agentTaxId', label: '代理資源公司統編', type: 'number' },
  { id: 'gridAddress', label: '併網所在地址', type: 'text' },
  { id: 'gridZip', label: '併網所在郵遞區號', type: 'number' },
  { id: 'area', label: '所屬區域', type: 'text' },
  { id: 'substation', label: '所屬變電所', type: 'text' },
  { id: 'feeder', label: '饋線', type: 'text' },
  { id: 'agentValidDate', label: '代理資源有效期限', type: 'date' },
  { id: 'maxAvailEnergy', label: '最大可運用電量(MWh)', type: 'number' },
  { id: 'minAvailEnergy', label: '最小可運用電量(MWh)', type: 'number' },
  { id: 'initAvailEnergy', label: '初始可運用電量(MWh)', type: 'number' },
  { id: 'lossRate', label: '責分點線損率', type: 'number' },
  { id: 'genGridVoltageKv', label: '發電機組-併網電壓等級(kV)', type: 'number' },
  { id: 'selfGenGridVoltageKv', label: '自用發電設備-併網電壓(kV)', type: 'number' },
  { id: 'feeCalcStart', label: '電能費計算起始日期', type: 'date' },
  { id: 'feeCalcEnd', label: '電能費計算結束日期', type: 'date' },
];
